site_name:
pages:
  - Home: 'index.md'
  - Experiments: 'experiments.md'
  - Analysis: 'analysis/index.md'
  - Results: 'results.md'
  - Code: 'code.md'
  - Reference: 'reference.md'
  - Log: 'log.md'
markdown_extensions:
  - toc
  - tables
  - fenced_code
  - footnotes
  - admonition
