# Calcualte surface area of all alkane carbon atoms for each frame

if { [llength $argv] != 2} {
puts "There are $argc arguments to this script"
puts "The name of this script is $argv0"
if { [llength $argv] > 0} {puts "The other arguments are: $argv" }

exit
}

set SysPdb [lindex $argv 0]
set TrjDCD [lindex $argv 1]

## first creat a new molecule at $SysMae and then append trajecotries to the molecule.
mol new $SysPdb
animate read dcd $TrjDCD waitfor all 0

## print number of frames in the current trajectory
puts [molinfo 0 get numframes]

set first [atomselect top protein frame 0]
set nf [molinfo top get numframes]
set outfile [open sarea_hydrophobic.dat w]
set nr 45

## calculate surface area for each residues and take an average number over the trajecotry.
for {set i 1} {$i < $nf} {incr i} {
     set allsel [atomselect top protein frame $i]
     set sel [atomselect top "protein and resid 1 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 1 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 1 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 1 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 1 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 2 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 2 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 2 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 2 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 3 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 3 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 3 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 3 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 4 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 4 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 4 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 4 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 5 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 5 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 5 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 6 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 6 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 6 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 6 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 6 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 6 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 7 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 7 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 7 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 8 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 8 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 8 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 8 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 8 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 9 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 9 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 9 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 10 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 10 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 10 and name CG2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 10 and name CG1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 10 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 10 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 11 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 11 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 11 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 11 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 11 and name CZ" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 11 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 12 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 12 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 12 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 12 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 12 and name CZ" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 12 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 13 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 13 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 13 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 13 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 13 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 13 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 14 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 14 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 14 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 14 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 14 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 14 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 15 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 15 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 15 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 16 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 16 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 16 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 16 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 16 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 17 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 17 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 17 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 17 and name CE1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 17 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 17 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 18 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 18 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 18 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 18 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 19 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 19 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 19 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 19 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 19 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 19 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 20 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 20 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 20 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 20 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 21 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 21 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 21 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 22 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 22 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 22 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 23 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 23 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 23 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 24 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 24 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 24 and name CG2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 24 and name CG1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 24 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 24 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 25 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 25 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 25 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 25 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 25 and name CE" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 25 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 26 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 26 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 27 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 27 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 27 and name CG2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 27 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 28 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 28 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 29 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 29 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 29 and name CG1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 29 and name CG2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 29 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 30 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 30 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 31 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 31 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 32 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 32 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 32 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 32 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 32 and name CZ" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 32 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 33 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 33 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 33 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 33 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 33 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 33 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 34 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 34 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 34 and name CG2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 34 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 35 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 35 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 35 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 35 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 35 and name CZ" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 35 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 36 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 36 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 36 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 36 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 36 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 37 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 37 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 37 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 37 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 38 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 38 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 38 and name CG1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 38 and name CG2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 38 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 39 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 39 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 39 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 39 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 39 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 40 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 40 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 40 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 40 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 40 and name CE" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 40 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 41 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 41 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 41 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 41 and name CE1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 41 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 41 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 42 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 42 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 42 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 42 and name CD1" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 42 and name CD2" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 42 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 43 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 43 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 43 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 44 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 44 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 44 and name CG" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 44 and name CD" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 44 and name CE" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 44 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 45 and name CA" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 45 and name CB" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 45 and name C" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
     set sel [atomselect top "protein and resid 46 and name CH3" frame $i]
     set rsasa [measure sasa 1.4 $allsel -restrict $sel]
     puts $outfile [format "%.2f" $rsasa]
}
exit
